language: node_js

node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
  - '6'

install:
  - node --version
  - npm --version
  - npm install

os:
  - osx
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - os: osx

script:
  - npm run lint
  - npm test

cache:
  directories:
    - node_modules
