# http://www.appveyor.com/docs/appveyor-yml

# Set build version format here instead of in the admin panel.
version: "{build}"

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "5"
    - nodejs_version: "4"
    - nodejs_version: "6"

# Finish on first failed build
matrix:
  fast_finish: true

# Install node, display versions, install dependencies
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version && npm --version
  - npm install

# Post-install test scripts.
test_script:
  - cmd: npm test

# Make clone much faster
shallow_clone: true

# Disable Visual Studio build and deploy
build: off
deploy: off

# Cache node modules, and refresh if package.json changes
cache:
  - node_modules -> package.json
